name: FE Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install
        working-directory: ./frontend
        run: |
          npm install

      - name: build
        working-directory: ./frontend
        run: |
          npm run build
          pwd
          ls -lta out

      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.2.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: echo install
          build_command: echo build
          build_directory: frontend/out